### ISSUE TITLE
Please read my e-mail

### ISSUE THREAD

**Issue by igneus** [Nocturnale-Romanum/website#1]
On Saturday I sent an e-mail to the address used in commits in this directory. I'm hereby trying to make sure that it won't pass completely unnoticed, e.g. swallowed by a spam filter or hanging forever in a mailbox which noone reads.

**Comment by xmarteo** [comment]
Hello @igneus, I do not, in fact, monitor the address you wrote to. Thanks for opening the issue, and a great many thanks for the email. I have pushed a fix, do check that it patches the hole.

**Comment by igneus** [comment]
Great, thanks, I've seen the fix, it should be OK now.
